import Link from "next/link";
import { ArrowRight, FileCheck2, Fingerprint, Gavel, Scale, ShieldCheck, Upload } from "lucide-react";
import { Reveal } from "@/components/reveal";

const claims = [
  { title: "Agent Failure", copy: "AI agents can act autonomously. When they fail, ProofCourt helps evaluate what happened through evidence and consensus.", examples: ["AI Trading Agent Loss", "Autonomous Execution Error", "Agent Misconduct", "Unauthorized Transaction", "AI Strategy Failure", "Data Leak Incident"] },
  { title: "Wallet Recovery", copy: "Lost devices, failed backups, and disputed recovery can leave digital assets inaccessible. ProofCourt replaces guesswork with an evidence-led process.", examples: ["Lost Device", "Hardware Wallet Failure", "Recovery Phrase Problem", "Backup Failure", "Multi-Sig Access Failure", "Wallet Corruption"] },
  { title: "Digital Continuity", copy: "Inheritance, beneficiary access, and long-term asset continuity create disputes conventional smart contracts cannot easily resolve.", examples: ["Beneficiary Access Request", "Inheritance Claim", "Account Continuity Request", "Emergency Recovery Request", "Family Verification", "Estate Settlement"] },
] as const;
const solution = [[FileCheck2, "01", "Submit Claim", "Describe the dispute and its claimed loss."], [Upload, "02", "Upload Evidence", "Private files remain off-chain."], [Fingerprint, "03", "Evidence Integrity", "SHA-256 fingerprints the submitted bytes."], [ShieldCheck, "04", "Evidence Verification", "Objective references are checked where supported."], [Gavel, "05", "GenLayer Consensus", "Validators evaluate the canonical claim."], [Scale, "06", "Verdict", "APPROVED, DENIED, or ESCALATED after finality."]] as const;
const verification = [[Fingerprint, "Evidence Integrity", "SHA-256", "Confirms the exact evidence submitted and detects later modification. It does not prove a file is truthful."], [Gavel, "Independent Review", "GenLayer Validators", "Validators independently evaluate the canonical claim under the contract’s defined rules."], [ShieldCheck, "Independent Sources", "Blockchain / Trusted Sources", "When a supported reference is supplied, ProofCourt can check objective on-chain transaction metadata. Broader sources are future work."]] as const;
const phases = [["01", "Evidence → Consensus → Verdict", "COMPLETED", "The working MVP: private evidence, canonical claims, GenLayer consensus, and an authoritative verdict."], ["02", "Evidence Verification Layer", "CURRENT / IN DEVELOPMENT", "Read-only objective GenLayer transaction metadata checks are the first safe addition."], ["03", "Multi-Source Evidence Intelligence", "FUTURE", "External sources, agent logs, additional model providers, and attestations."], ["04", "Insurance Pool & Payouts", "FUTURE", "Policies, premiums, coverage limits, claim eligibility, and payouts."], ["05", "Decentralized Insurance Marketplace", "FUTURE", "Liquidity providers, risk pools, coverage markets, and decentralized capital allocation."]] as const;

export default function Home() { return <>
  <section className="hero container"><Reveal className="hero-copy"><p className="eyebrow">ProofCourt</p><h1>Evidence. Consensus.<br /><em>Verdict.</em></h1><p className="lede">AI-powered insurance adjudication built on GenLayer.</p><p className="lede hero-subhead">Submit evidence. Let GenLayer validators review. Receive a transparent verdict.</p><div className="hero-actions"><Link className="button button-quiet" href="/demo">Run Demo</Link><Link className="button" href="/claim">Submit Claim <ArrowRight size={17} /></Link></div></Reveal><div className="hero-flow hero-flow-animated" aria-label="ProofCourt claim process"><div><span>01</span><strong>Evidence</strong><i /></div><div><span>02</span><strong>Consensus</strong><i /></div><div><span>03</span><strong>Verdict</strong><span className="flow-live">LIVE</span></div></div></section>
  <section className="band"><Reveal className="container split"><div><p className="eyebrow">The problem</p><h2>When Digital Claims Become Disputed</h2></div><div><p>Digital disputes are difficult to resolve because evidence exists, but trust does not. Traditional systems struggle when real-world evidence requires reasoning and judgment.</p><p>ProofCourt helps resolve agent, wallet, and continuity disputes through evidence, defined policy rules, and GenLayer consensus.</p></div></Reveal></section>
  <section id="claim-types" className="container section"><Reveal><p className="eyebrow">Claim categories</p><h2>Three kinds of digital responsibility.</h2></Reveal><div className="three-grid claim-grid">{claims.map((claim, index) => <Reveal className="reveal-grid-item" delay={index * 90} key={claim.title}><article className="card claim-card"><span className="number">0{index + 1}</span><h3>{claim.title}</h3><p>{claim.copy}</p><ul>{claim.examples.map(example => <li key={example}>{example}</li>)}</ul></article></Reveal>)}</div></section>
  <section id="how-it-works" className="band"><div className="container"><Reveal><p className="eyebrow">The solution</p><h2>ProofCourt Solves All Three</h2><p className="lede">ProofCourt combines evidence integrity, independent verification where possible, and GenLayer consensus to evaluate agent liability, wallet recovery, and digital continuity claims.</p></Reveal><div className="solution-grid">{solution.map(([Icon, number, title, copy], index) => <Reveal className="reveal-grid-item" delay={index * 75} key={title}><article className="process solution-step"><Icon /><span>{number}</span><h3>{title}</h3><p>{copy}</p></article></Reveal>)}</div><Reveal><p className="integrity-note"><strong>Integrity is not authenticity.</strong> A hash confirms the submitted file has not changed; it does not by itself prove that the content is true.</p></Reveal></div></section>
  <section className="container section verification-section"><Reveal><p className="eyebrow">Evidence verification</p><h2>Who verifies the evidence?</h2><p className="lede">Anyone can upload a file. That does not make it true. Screenshots can be edited, logs can be fabricated, and wallet records can be misleading.</p><p className="lede">ProofCourt is designed to compare submitted evidence with independent sources whenever those sources are available.</p></Reveal><Reveal><ol className="verification-flow" aria-label="Layered evidence verification"><li>Submitted Evidence</li><li>Evidence Fingerprint</li><li>Content Verification · Future</li><li>Independent Source Verification · Where Supported</li><li>GenLayer Validator Review</li><li>Evidence Assessment</li></ol></Reveal><div className="three-grid verification-grid">{verification.map(([Icon, title, label, copy], index) => <Reveal className="reveal-grid-item" delay={index * 100} key={title}><article className="card verification-card"><Icon /><span className="number">{label}</span><h3>{title}</h3><p>{copy}</p></article></Reveal>)}</div><Reveal><p className="verification-boundary"><strong>Current Phase 2 boundary:</strong> ProofCourt can locate an optional GenLayer transaction reference and record objective public metadata such as lifecycle, sender, recipient, and value. That check is not proof that any uploaded document, image, receipt, or log is truthful—or related to that transaction.</p></Reveal></section>
  <section id="why-genlayer" className="band"><Reveal className="container split"><div><p className="eyebrow">Why GenLayer</p><h2>Evidence needs decentralized reasoning.</h2></div><div><p>Traditional smart contracts execute deterministic rules. ProofCourt needs to evaluate evidence and judgment, while keeping final authority decentralized.</p><p>GenLayer Intelligent Contracts can use web data, LLM reasoning, image processing, and blockchain information where an implementation deliberately supplies and validates them. Validators independently evaluate the proposed result through GenLayer’s consensus and equivalence model; ProofCourt never treats one centralized AI response as the verdict.</p></div></Reveal></section>
  <section className="container section product-explainer"><Reveal><p className="eyebrow">ProofCourt at a glance</p><h2>Insurance adjudication powered by evidence and GenLayer consensus.</h2></Reveal><div className="four-grid"><Reveal className="reveal-grid-item"><article className="process"><span>01</span><h3>What is ProofCourt?</h3><p>Insurance adjudication powered by evidence and GenLayer consensus.</p></article></Reveal><Reveal className="reveal-grid-item" delay={80}><article className="process"><span>02</span><h3>Who is it for?</h3><p>Agent operators, wallet owners, beneficiaries, and digital asset holders.</p></article></Reveal><Reveal className="reveal-grid-item" delay={160}><article className="process"><span>03</span><h3>How does it work?</h3><p>Evidence is submitted, verified where possible, and evaluated through validator consensus.</p></article></Reveal><Reveal className="reveal-grid-item" delay={240}><article className="process"><span>04</span><h3>What is the outcome?</h3><p>APPROVED, DENIED, or ESCALATED—only after an authoritative finalized result.</p></article></Reveal></div></section>
  <section id="roadmap" className="band"><div className="container"><Reveal><p className="eyebrow">Roadmap</p><h2>Building the future of decentralized insurance adjudication.</h2></Reveal><div className="roadmap">{phases.map(([number, title, status, copy], index) => <Reveal className="reveal-grid-item" delay={index * 70} key={number}><article className={`roadmap-item ${status === "COMPLETED" ? "completed" : status.startsWith("CURRENT") ? "current" : "future"}`}><span className="roadmap-number">PHASE {number}</span><div><span className="roadmap-status">{status}</span><h3>{title}</h3><p>{copy}</p></div></article></Reveal>)}</div></div></section>
  <section className="container cta"><Reveal><p className="eyebrow">A court for disputed digital claims</p><h2>Make your case.</h2><p>Start with a safe simulation, or submit a claim to the configured live GenLayer workflow.</p><div className="hero-actions"><Link className="button button-quiet" href="/demo">Run Demo</Link><Link className="button" href="/claim">Submit Claim <ArrowRight size={17} /></Link></div></Reveal></section>
</>; }
