import Link from "next/link";
import { ArrowRight, Fingerprint, Network, ShieldCheck } from "lucide-react";
import { CinematicHero } from "@/components/cinematic-hero";
import { Reveal } from "@/components/reveal";

const responsibilities = [
  ["01", "Agent failure", "Disputes involving autonomous agent decisions."],
  ["02", "Wallet recovery", "Evidence-based adjudication for lost or inaccessible wallets and digital assets."],
  ["03", "Digital continuity", "Evidence and responsibility when critical digital systems are disrupted."],
] as const;
const stages = [["01", "Evidence", "Submit a clear account of the event and its supporting records."], ["02", "Verification", "Fingerprint evidence and verify supported public references."], ["03", "Consensus", "Independent validators evaluate the canonical claim."], ["04", "Verdict", "The contract returns an authoritative structured outcome."], ["05", "Finality", "The completed lifecycle makes the decision durable."]] as const;
const roadmap = [["01", "Evidence → Consensus → Verdict", "LIVE MVP", "Private evidence, canonical claims, validator consensus, and authoritative results."], ["02", "Evidence verification layer", "LIVE MVP", "Evidence integrity and supported, opt-in public-source verification."], ["03", "Broader evidence sources", "NEXT", "Additional attestations, agent logs, and carefully bounded public references."], ["04", "Agent liability coverage", "FUTURE", "Policies, premiums, coverage limits, and claim eligibility."], ["05", "Decentralized risk marketplace", "FUTURE", "Insurance pools, coverage markets, and risk capital."]] as const;

export default function Home() { return <>
  <CinematicHero />
  <section className="pc-problem"><Reveal className="pc-shell pc-problem-grid"><p className="pc-kicker">The problem</p><h2>When digital events<br />become disputed.</h2><div className="pc-problem-copy"><p>Agents can make harmful, unauthorized, or policy-violating decisions. Wallets can become lost or inaccessible. Critical digital responsibilities can be disrupted.</p><p>ProofCourt gives these events a structured path from evidence to a verdict.</p></div></Reveal></section>
  <section id="claim-types" className="pc-section pc-shell"><Reveal><p className="pc-kicker">Three responsibilities</p><h2 className="pc-display">A court for the new<br />digital responsibility.</h2></Reveal><div className="pc-responsibilities">{responsibilities.map(([number, title, copy], index) => <Reveal delay={index * 90} key={title}><article className="pc-responsibility"><div className={`pc-card-art pc-art-${index + 1}`} aria-hidden="true"><i /><i /><i /></div><span>{number}</span><h3>{title}</h3><p>{copy}</p><ArrowRight size={18} /></article></Reveal>)}</div></section>
  <section id="how-it-works" className="pc-process"><div className="pc-shell"><Reveal><p className="pc-kicker">How ProofCourt works</p><div className="pc-process-heading"><h2 className="pc-display">A path from<br />event to finality.</h2><p>Every step narrows ambiguity without turning a single model or party into the authority.</p></div></Reveal><div className="pc-process-track">{stages.map(([number, title, copy], index) => <Reveal delay={index * 70} key={title}><article className="pc-stage"><span>{number}</span><div className="pc-stage-dot"><i /></div><h3>{title}</h3><p>{copy}</p></article></Reveal>)}</div></div></section>
  <section className="pc-section pc-shell pc-evidence"><Reveal><p className="pc-kicker">Evidence verification</p><h2 className="pc-display">What a file can<br />and cannot prove.</h2></Reveal><div className="pc-evidence-grid"><Reveal><article><Fingerprint /><p className="pc-label">Evidence integrity</p><h3>The exact submitted bytes.</h3><p>SHA-256 hashing identifies the submitted evidence and detects later modification. A hash does not prove that evidence is truthful.</p></article></Reveal><Reveal delay={100}><article><ShieldCheck /><p className="pc-label">Evidence interpretation</p><h3>Independent, where supported.</h3><p>Optional immutable public evidence can be independently retrieved and evaluated by validators. Public-source verification is never mandatory.</p></article></Reveal></div></section>
  <section id="why-genlayer" className="pc-genlayer"><div className="pc-shell pc-genlayer-grid"><Reveal><div><p className="pc-kicker">Why GenLayer</p><h2 className="pc-display">Reasoning needs<br />more than one voice.</h2><p className="pc-genlayer-copy">ProofCourt uses a GenLayer Intelligent Contract to move adjudication through validator-backed consensus—not a trusted leader result.</p></div></Reveal><Reveal delay={120}><div className="pc-validator-field" aria-label="Illustrative validator consensus visualization"><span>Validator consensus</span><div className="pc-validator-lines" aria-hidden="true"><i /><i /><i /></div><div className="pc-validator-nodes" aria-hidden="true"><b>01</b><b>02</b><b>03</b><b>04</b><b>05</b><strong><Network size={22} /></strong></div><p>Independent validation turns a proposed result into a shared decision.</p></div></Reveal></div></section>
  <section className="pc-demo pc-shell"><Reveal><div><p className="pc-kicker">Live demo</p><h2 className="pc-display">See the workflow<br />in motion.</h2></div><div className="pc-demo-side"><p>Explore the isolated claim simulation, then submit a live claim only when you are ready.</p><Link className="pc-text-link" href="/demo">Run the live demo <ArrowRight size={17} /></Link></div></Reveal></section>
  <section id="roadmap" className="pc-roadmap"><div className="pc-shell"><Reveal><p className="pc-kicker">Roadmap</p><h2 className="pc-display">Designed for the<br />longer horizon.</h2></Reveal><div className="pc-roadmap-list">{roadmap.map(([number, title, state, copy], index) => <Reveal delay={index * 65} key={number}><article className="pc-roadmap-row"><span>{number}</span><div><b className={state === "LIVE MVP" ? "is-live" : ""}>{state}</b><h3>{title}</h3><p>{copy}</p></div></article></Reveal>)}</div></div></section>
  <section className="pc-final"><Reveal className="pc-shell"><p className="pc-kicker">ProofCourt</p><h2>When the digital world disputes what happened, ProofCourt creates a path to a verdict.</h2><div><Link className="button" href="/claim">Submit a claim <ArrowRight size={17} /></Link><Link className="pc-text-link" href="/#how-it-works">Explore the workflow <ArrowRight size={17} /></Link></div></Reveal></section>
</>; }
