import Link from "next/link";
import { ArrowRight, FileCheck2, Gavel, ShieldCheck, Upload } from "lucide-react";

const cards = [
  ["Agent Failure", "Claims involving AI agent losses, misconduct, execution errors, or data leaks."],
  ["Wallet Recovery", "Claims involving lost access, recovery failures, and wallet disputes."],
  ["Digital Continuity", "Claims involving inheritance, beneficiaries, and digital asset succession."],
  ["GenLayer Consensus", "Validators evaluate evidence and reach a transparent verdict."],
];
const steps = [[FileCheck2, "1", "Submit Claim"], [Upload, "2", "Upload Evidence"], [ShieldCheck, "3", "Evidence is hashed"], [Gavel, "4", "GenLayer Intelligent Contract"], [Gavel, "5", "Validators evaluate"], [ShieldCheck, "6", "Consensus and verdict"]] as const;

export default function Home() { return <>
  <section className="hero container"><div><p className="eyebrow">ProofCourt</p><h1>Evidence. Consensus.<br /><em>Verdict.</em></h1><p className="lede">AI-powered insurance adjudication for agent failures, wallet recovery, and digital continuity claims—secured by GenLayer consensus.</p><p className="lede">Submit evidence. Let GenLayer validators review. Receive a transparent verdict.</p><div className="hero-actions"><Link className="button button-quiet" href="/demo">Run Demo</Link><Link className="button" href="/claim">Submit Claim <ArrowRight size={17} /></Link></div></div><div className="hero-flow" aria-label="Insurance Court flow"><div><span>01</span><strong>Insurance Court</strong></div><i /><div><span>02</span><strong>Evidence Submitted</strong></div><i /><div><span>03</span><strong>GenLayer Consensus</strong></div><i /><div><span>04</span><strong>Verdict</strong></div></div></section>
  <section className="band"><div className="container split"><div><p className="eyebrow">The problem</p><h2>When Digital Claims Become Disputed</h2></div><div><p>AI agents fail. Wallets become inaccessible. Recovery processes break. Digital inheritance becomes contested. Traditional smart contracts cannot reason about evidence.</p></div></div></section>
  <section id="solution" className="container section"><p className="eyebrow">The solution</p><h2>ProofCourt turns evidence into a transparent verdict.</h2><p className="lede">Submit evidence. GenLayer validators evaluate the claim. Consensus determines the outcome. Receive a transparent verdict.</p><div className="four-grid">{steps.map(([Icon, number, title]) => <article className="process" key={title}><Icon /><span>{number}</span><h3>{title}</h3></article>)}</div></section>
  <section id="claim-types" className="container section"><p className="eyebrow">Claim types</p><h2>Designed for digital responsibility.</h2><div className="four-grid">{cards.map(([title, text], index) => <article className="card" key={title}><span className="number">0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section id="how-it-works" className="band"><div className="container split"><div><p className="eyebrow">How it works</p><h2>From filing a case to a court decision.</h2></div><div><p>Upload evidence; ProofCourt hashes it, sends the canonical claim to the GenLayer Intelligent Contract, and lets validators independently evaluate it. After consensus and finality, ProofCourt retrieves the authoritative contract result and displays it transparently.</p><p><strong>Demo Mode</strong> is an isolated simulation with no backend, wallet, or blockchain activity. <strong>Live GenLayer Mode</strong> submits only when the server has configured credentials and a deployed contract.</p></div></div></section>
  <section id="why-genlayer" className="container section"><p className="eyebrow">Why GenLayer</p><h2>Evidence needs decentralized reasoning.</h2><p className="lede">Traditional smart contracts are deterministic and cannot naturally reason over complex evidence. ProofCourt uses GenLayer’s validator-based consensus around Intelligent Contract execution; it does not treat a transaction submission as a verdict.</p></section>
  <section className="container cta"><p className="eyebrow">A court for disputed digital claims</p><h2>Make your case.</h2><Link className="button" href="/claim">Submit Claim <ArrowRight size={17} /></Link></section>
</>; }
