"use client";
import { useMemo, useRef, useState } from "react";
import Link from "next/link";
import { FileText, Trash2, UploadCloud, AlertCircle, ArrowLeft, ArrowRight, ShieldCheck } from "lucide-react";
import type { ClaimDraft, ClaimType, Evidence } from "@/types/claims";
import { bytes, money } from "@/lib/format";
import { StatusBadge } from "@/components/status";
import { claimApi } from "@/services/claims";

const initial: ClaimDraft = { type: "AGENT_FAILURE", incidentCategory: "AI Trading Agent Loss", title: "", description: "", incidentAt: "", lossAmount: "", currency: "USD", agentIdentifier: "", referenceId: "", policyId: "" };
const types: { value: ClaimType; title: string; text: string }[] = [{ value: "AGENT_FAILURE", title: "Agent Failure", text: "Claims involving AI agent losses, misconduct, execution errors, or data leaks." }, { value: "WALLET_RECOVERY", title: "Wallet Recovery", text: "Claims involving lost access, recovery failures, and wallet disputes." }, { value: "DIGITAL_CONTINUITY", title: "Digital Continuity", text: "Claims involving inheritance, beneficiaries, and digital asset succession." }];
const incidents: Record<ClaimType, string[]> = { AGENT_FAILURE: ["AI Trading Agent Loss", "Autonomous Execution Error", "Agent Misconduct", "Unauthorized Transaction", "AI Strategy Failure", "Data Leak Incident", "Prompt Injection Attack", "Agent Permission Abuse", "Incorrect Financial Action", "Failed Autonomous Task"], WALLET_RECOVERY: ["Lost Device", "Hardware Wallet Failure", "Recovery Phrase Problem", "Backup Failure", "Multi-Sig Access Failure", "Wallet Corruption", "Locked Wallet Access", "Recovery Process Failure", "Account Access Dispute", "Wallet Migration Failure"], DIGITAL_CONTINUITY: ["Beneficiary Access Request", "Inheritance Claim", "Estate Settlement", "Emergency Recovery Request", "Account Continuity Request", "Family Verification", "Guardian Activation Request", "Digital Asset Succession", "Ownership Verification", "Legacy Access Claim"] };
const allowed = ["application/pdf", "image/jpeg", "image/png", "text/plain"];
const maxSize = 10 * 1024 * 1024;

export function ClaimFlow() {
  const [step, setStep] = useState(0); const [draft, setDraft] = useState(initial); const [evidence, setEvidence] = useState<Evidence[]>([]); const [files, setFiles] = useState<Record<string, File>>({}); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const fileInput = useRef<HTMLInputElement>(null);
  const update = (key: keyof ClaimDraft, value: string) => setDraft(previous => ({ ...previous, [key]: value }));
  const valid = useMemo(() => step === 0 || (step === 1 ? Boolean(draft.incidentCategory && draft.title && draft.description && draft.incidentAt && Number(draft.lossAmount) > 0) : step === 2 ? evidence.length > 0 && evidence.every(item => item.status === "READY") : true), [step, draft, evidence]);
  function addFiles(selection: FileList | File[]) { setError(""); for (const file of Array.from(selection)) { if (!allowed.includes(file.type)) { setError("Use PDF, JPG, PNG, or TXT evidence only."); continue; } if (file.size > maxSize) { setError("Each evidence file must be 10 MB or smaller."); continue; } if (evidence.some(item => item.filename === file.name && item.size === file.size)) { setError("That evidence file is already attached."); continue; } const id = crypto.randomUUID(); setFiles(old => ({ ...old, [id]: file })); setEvidence(old => [...old, { id, filename: file.name, mimeType: file.type, size: file.size, status: "READY" }]); } }
  async function submit() { setSubmitting(true); setError(""); try { const key = crypto.randomUUID(); const claim = await claimApi.create(draft, key); for (const item of evidence) await claimApi.uploadEvidence(claim.id, files[item.id]); const active = await claimApi.adjudicate(claim.id, key); window.location.assign(`/review/${active.id}`); } catch (caught) { const response = caught as Error & { status?: number; data?: { claimId?: string } }; if (response.status === 409 && response.data?.claimId) window.location.assign(`/review/${response.data.claimId}`); else setError(response.message || "Your claim could not be submitted. Check your connection and try again."); setSubmitting(false); } }
  return <section className="container flow"><div className="eyebrow">Agent Liability Insurance</div><h1>Submit a claim</h1><p className="lede">Provide only the details needed to evaluate the event. Never share a private key, seed phrase, password, or API secret.</p><ol className="steps" aria-label="Claim submission steps">{["Claim type", "Incident", "Evidence", "Review", "Submit"].map((label, index) => <li className={index === step ? "current" : index < step ? "complete" : ""} key={label}><span>{index + 1}</span>{label}</li>)}</ol><div className="flow-card">
    {step === 0 && <fieldset><legend>What type of case are you filing?</legend><div className="type-grid">{types.map(type => <label className={`type-card ${draft.type === type.value ? "selected" : ""}`} key={type.value}><input type="radio" name="type" checked={draft.type === type.value} onChange={() => setDraft(previous => ({ ...previous, type: type.value, incidentCategory: incidents[type.value][0] }))} /><strong>{type.title}</strong><span>{type.text}</span></label>)}</div></fieldset>}
    {step === 1 && <fieldset><legend>Describe the incident</legend><div className="form-grid"><label>Incident category<select value={draft.incidentCategory} onChange={e => update("incidentCategory", e.target.value)}>{incidents[draft.type].map(category => <option key={category}>{category}</option>)}</select></label><label>Incident title<input value={draft.title} onChange={e => update("title", e.target.value)} maxLength={120} required /></label><label>Date and time of incident<input type="datetime-local" value={draft.incidentAt} onChange={e => update("incidentAt", e.target.value)} required /></label><label className="full">What happened?<textarea value={draft.description} onChange={e => update("description", e.target.value)} maxLength={4000} required /></label><label>Claimed loss amount<input type="number" min="0" step="0.01" value={draft.lossAmount} onChange={e => update("lossAmount", e.target.value)} required /></label><label>Currency<select value={draft.currency} onChange={e => update("currency", e.target.value)}><option>USD</option><option>EUR</option><option>GBP</option><option>GEN</option></select></label><label>Agent identifier <small>(if applicable)</small><input value={draft.agentIdentifier} onChange={e => update("agentIdentifier", e.target.value)} /></label><label>Transaction/reference ID <small>(if applicable)</small><input value={draft.referenceId} onChange={e => update("referenceId", e.target.value)} /></label><label>Policy information <small>(if applicable)</small><input value={draft.policyId} onChange={e => update("policyId", e.target.value)} /></label></div></fieldset>}
    {step === 2 && <fieldset><legend>Add supporting evidence</legend><p className="field-help">Evidence stays off-chain. The backend validates and creates the authoritative hash after upload.</p><input ref={fileInput} className="sr-only" id="evidence" type="file" accept=".pdf,.jpg,.jpeg,.png,.txt" multiple onChange={e => e.target.files && addFiles(e.target.files)} /><label className="dropzone" htmlFor="evidence" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); addFiles(e.dataTransfer.files); }}><UploadCloud size={28} /><strong>Drop files here or browse</strong><span>PDF, JPG, PNG, TXT · up to 10 MB each</span></label>{evidence.length === 0 ? <p className="empty">No evidence added yet. Attach at least one item to continue.</p> : <ul className="evidence-list">{evidence.map(item => <li key={item.id}><FileText /><div><strong>{item.filename}</strong><span>{item.mimeType} · {bytes(item.size)} · <StatusBadge status={item.status} /></span></div><button className="icon-button" onClick={() => { setEvidence(old => old.filter(x => x.id !== item.id)); setFiles(old => { const copy = { ...old }; delete copy[item.id]; return copy; }); }} aria-label={`Remove ${item.filename}`}><Trash2 size={18} /></button></li>)}</ul>}</fieldset>}
    {step === 3 && <section aria-labelledby="review-title"><h2 id="review-title">Review your claim</h2><div className="review-grid"><div><span>Claim type</span><strong>{types.find(x => x.value === draft.type)?.title}</strong></div><div><span>Claimed loss</span><strong>{money(Number(draft.lossAmount), draft.currency)}</strong></div><div className="full"><span>Incident</span><strong>{draft.title}</strong><p>{draft.description}</p></div><div className="full"><span>Evidence ({evidence.length})</span>{evidence.map(item => <p key={item.id}>{item.filename} · {bytes(item.size)}</p>)}</div></div><aside className="notice"><ShieldCheck size={20} /><span>Once submitted, this claim will enter the GenLayer adjudication process. Submission does not mean a verdict or payment.</span></aside></section>}
    {step === 4 && <section className="submit-panel"><ShieldCheck size={30} /><h2>Ready to submit</h2><p>We’ll create the claim, upload your evidence, then request adjudication. This can’t be undone from this screen.</p><button className="button" disabled={submitting} onClick={submit}>{submitting ? "Submitting claim…" : "Submit claim"}</button></section>}
    {error && <p className="error" role="alert"><AlertCircle size={18} />{error}</p>}<div className="flow-actions">{step > 0 ? <button className="button button-quiet" onClick={() => setStep(value => value - 1)} disabled={submitting}><ArrowLeft size={17} />Back</button> : <Link className="button button-quiet" href="/"><ArrowLeft size={17} />Cancel</Link>}{step < 4 && <button className="button" onClick={() => setStep(value => value + 1)} disabled={!valid}>Continue<ArrowRight size={17} /></button>}</div>
  </div></section>;
}
